### ISSUE TITLE
could you enable php7-opcache in alphp-base?

### ISSUE THREAD

**Issue by scil** [inhere/alphp#5]
I'd love this project, and I think opcache is very basic. Could you enable it please?

**Comment by limingxinleo** [comment]
You can rewrite it by yourself.

For example,

https://github.com/limingxinleo/swoft-project/blob/master/Dockerfile

**Comment by scil** [comment]
Thank you.

I just want this Dockerfile here more adaptable and friendly in most cases.

**Comment by daydaygo** [comment]
@scil base is used by almost other images, and opcache may not be need by all other, how about enable it int the `swoft/alphp:dev` image?

**Comment by scil** [comment]
Good idea! 
Thank you!
